begin;

create table if not exists public.planner_layouts (
  id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.planner_layouts_backup (
  id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.planner_audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_name text not null,
  action text not null,
  entity_type text not null,
  entity_name text,
  detail text
);

-- The official project already has public.collaborators with a different contract.
-- Keep the planner team isolated instead of changing that production table.
create table if not exists public.planner_collaborators (
  id text primary key,
  name text not null,
  role text not null default 'Colaborador',
  color text not null default 'oklch(0.62 0.18 255)',
  photo_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  email text,
  user_id uuid references auth.users(id) on delete set null,
  source_user_id uuid,
  is_admin boolean not null default false,
  can_add boolean not null default true,
  can_edit boolean not null default false,
  can_move boolean not null default false,
  can_manage_collaborators boolean not null default false,
  access_requested_at timestamptz
);

create or replace function public.set_asset_planner_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'UPDATE' and new.updated_at is not distinct from old.updated_at then
    new.updated_at = now();
  end if;
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'planner_layouts_set_updated_at'
      and tgrelid = 'public.planner_layouts'::regclass
  ) then
    create trigger planner_layouts_set_updated_at
      before update on public.planner_layouts
      for each row execute function public.set_asset_planner_updated_at();
  end if;

  if not exists (
    select 1 from pg_trigger
    where tgname = 'planner_collaborators_set_updated_at'
      and tgrelid = 'public.planner_collaborators'::regclass
  ) then
    create trigger planner_collaborators_set_updated_at
      before update on public.planner_collaborators
      for each row execute function public.set_asset_planner_updated_at();
  end if;
end;
$$;

alter table public.planner_layouts enable row level security;
alter table public.planner_layouts_backup enable row level security;
alter table public.planner_audit_log enable row level security;
alter table public.planner_collaborators enable row level security;

do $$
declare
  target_table text;
  policy_name text;
begin
  foreach target_table in array array[
    'planner_layouts',
    'planner_layouts_backup',
    'planner_audit_log',
    'planner_collaborators'
  ] loop
    policy_name := target_table || '_admin_all';
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
        and tablename = target_table
        and policyname = policy_name
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()))',
        policy_name,
        target_table
      );
    end if;
  end loop;
end;
$$;

grant select, insert, update, delete on public.planner_layouts to authenticated;
grant select, insert, update, delete on public.planner_layouts_backup to authenticated;
grant select, insert on public.planner_audit_log to authenticated;
grant usage, select on sequence public.planner_audit_log_id_seq to authenticated;
grant select, insert, update, delete on public.planner_collaborators to authenticated;

insert into storage.buckets (id, name, public)
values ('asset-files', 'asset-files', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'asset_files_admin_insert'
  ) then
    create policy asset_files_admin_insert on storage.objects
      for insert to authenticated
      with check (bucket_id = 'asset-files' and public.is_admin(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'asset_files_admin_update'
  ) then
    create policy asset_files_admin_update on storage.objects
      for update to authenticated
      using (bucket_id = 'asset-files' and public.is_admin(auth.uid()))
      with check (bucket_id = 'asset-files' and public.is_admin(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'asset_files_admin_delete'
  ) then
    create policy asset_files_admin_delete on storage.objects
      for delete to authenticated
      using (bucket_id = 'asset-files' and public.is_admin(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'asset_files_admin_select'
  ) then
    create policy asset_files_admin_select on storage.objects
      for select to authenticated
      using (bucket_id = 'asset-files' and public.is_admin(auth.uid()));
  end if;
end;
$$;

commit;
